apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db-deployment
  namespace: final
  labels:
    appname: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: mysql
  template:
    metadata:
      labels:
        appname: mysql
    spec:
      containers:
      - name: mysql
        image: 055686730858.dkr.ecr.us-east-1.amazonaws.com/mysql-db:my_db
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-config
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - mountPath: /tmp/data
          name: final-pv
      imagePullSecrets:
      - name: creds-test-1
      volumes:
      - name: final-pv
        persistentVolumeClaim:
          claimName: app-final-pvc
