apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db-deployment
  namespace: final
  labels:
    appname: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: mysql
  template:
    metadata:
      labels:
        appname: mysql
    spec:
      containers:
      - name: mysql
        image: 584918656742.dkr.ecr.us-east-1.amazonaws.com/mysql-db
        ports:
        - containerPort: 3306
        env:
        # Reference the db-config secret
        - name: DBHOST
          valueFrom:
            secretKeyRef:
              name: db-config
              key: DBHOST
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: db-config
              key: DBUSER
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: db-config
              key: DBPWD
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: db-config
              key: DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-config
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - mountPath: /tmp/data
          name: final-pv
      imagePullSecrets:
      - name: creds-test
      volumes:
      - name: final-pv
        persistentVolumeClaim:
          claimName: app-final-pvc