apiVersion: apps/v1
kind: Deployment
metadata:
  name: clo835-mysql-nodeapp-final
  namespace: final
  labels:
    app: clo835-mysql-nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clo835-mysql-nodeapp
  template:
    metadata:
      labels:
        app: clo835-mysql-nodeapp
    spec:
      containers:
        - name: mysql
          image: 584918656742.dkr.ecr.us-east-1.amazonaws.com/final_project:g13
          ports:
            - containerPort: 3306
          env:
            - name: DBHOST
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DBHOST
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DBUSER
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DBPWD
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /tmp/data
              name: app-final-volume  
        - name: node-app
          image: 584918656742.dkr.ecr.us-east-1.amazonaws.com/final_project:g13
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /tmp/data
              name: app-final-volume
      imagePullSecrets:
        - name: creds-test
      volumes:
        - name: app-final-volume
          persistentVolumeClaim:
            claimName: app-final-pvc