kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-final-pvc
  namespace: final
  labels:
    app: final_g13
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi