apiVersion: v1
kind: Secret
metadata:
  name: db-config
  namespace: final
type: Opaque
data:
  DBHOST: c3FsZGItc2VydmljZS5zcWxkYi5zdmMuY2x1c3Rlci5sb2NhbA==
  DBUSER: cm9vdA==
  DBPWD: cGFzc3dvcmQ=
  DATABASE: ZW1wbG95ZWVz
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=