apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clo835-g13-rolebinding
  namespace: final
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: clo835-g13-role
subjects:
- kind: ServiceAccount
  name: clo835-final-g13
  namespace: final
