kind: PersistentVolume
apiVersion: v1
metadata:
  name: final-pv
  namespace: final
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  awsElasticBlockStore:
    volumeID: "vol-08439e1e1b23d34fb"
    fsType: ext4